### ISSUE TITLE
Chaning Tree / Background per level

### ISSUE THREAD

**Issue by mckenziedave** [MattSurabian/DuckHunt-JS#17]
Hi Everyone,
So I have been editing this game and using it for practice while learning JavaScript so far I have edited it so there are 3 levels (each with different ducks, diffculty etc) I also have the sky change from day to night through the levels the only problem is now the tree / grass is annoying me as when its night the grass it still a bright green. I was wondering is there a way to change the tree / grass etc per level? If so how can this be achieved?

Cheers

**Comment by MattSurabian** [comment]
I'd suggest doing the same thing you've done in #16, only using the level data to store a path to the image you want to use. Then somewhere near the end of the [loadLevel](https://github.com/MattSurabian/DuckHunt-JS/blob/master/duckhunt/duckhunt.js#L95) method use jquery to adjust the `background-image` CSS property. It would look something like this:

```
$('.grass').css('background-image', 'url(' + this.level.backgroundImage + ')');
```

**Comment by MattSurabian** [comment]
Closing this issue, but feel free to reopen if you still have questions!

**Comment by mckenziedave** [comment]
Hi Matt thank you for the reply, hope you had a great christmas! I was playing around with the code last night / this morning however couldnt get it to work... I understand the same solution as in 16 however can seem to execute it? What would i need to have for each level in level.js? .backgroundImage?... Thank you for your help

**Comment by MattSurabian** [comment]
Thanks @mckenziedave! I did have a nice Christmas, hopefully you did as well.

Regarding the levels.js additions something like this should work:

```
    {
        id: 1,
        title: 'Level 1',
        waves: 3,
        ducks: 2,
        pointsPerDuck: 100,
        speed: 5,
        bullets: 3,
        time: 13,
        backgroundImage: 'images/level1back.png'
    }
```

I haven't tested this out, but it's possible you'll need to override the existing background like this:

```
$('.grass').css('background', 'url(' + this.level.backgroundImage + ') bottom left no-repeat');
```

and not like above because of [how it's declared in the css file](https://github.com/MattSurabian/DuckHunt-JS/blob/master/style.css#L55-L62). Also, ensure that you're making that call [after this line](https://github.com/MattSurabian/DuckHunt-JS/blob/master/duckhunt/duckhunt.js#L100).

If you have any code snippets or errors available to post I might be able to offer some more suggestions.

**Comment by MattSurabian** [comment]
I'll leave this issue open until I hear confirmation you've got this working, or one week passes.

**Comment by mckenziedave** [comment]
Hi Matt, I have added the code within the level.js

var levels = [
    {
        id: 1,
        title: 'Hit all the Crabs',
        waves: 1,
        ducks: 10,
        pointsPerDuck: 100,
        speed: 1,
        bullets: 20,
        backgroundColor: '#F3936B',
        time: 30
        backgroundImage: 'images/level1back.png'
    },

and also added the code within the duckhunt.js for the overide however no background is changed and the the game doesnt seem to start now? (I never see the hit all ducks message and no bullets etc show??) Not sure what has gone wrong?

**Comment by MattSurabian** [comment]
In the snippet above you're missing a coma after `time: 30`; should be:

```
{
id: 1,
title: 'Hit all the Crabs',
waves: 1,
ducks: 10,
pointsPerDuck: 100,
speed: 1,
bullets: 20,
backgroundColor: '#F3936B',
time: 30,
backgroundImage: 'images/level1back.png'
},
```

Also depending on what browser you're in the developer tools console should be able to provide some good feedback on what has gone wrong if that's not it.

**Comment by mckenziedave** [comment]
Hi Matt,
Little embarrassed! How did I miss that. Thank you so much problem solved! Hope you have a great New Year! :+1:

**Comment by MattSurabian** [comment]
Don't worry about it, I've missed many a comma. Have a great New Year! :fireworks:
