### ISSUE TITLE
onTouch  for mobile support

### ISSUE THREAD

**Issue by emotality** [MattSurabian/DuckHunt-JS#18]
Hi Matt! :smiley: 

Good job on this game, we love it! :)

I see you opened an issue (#10) for mobile support:
> "...and address a lot of the mobile/refactor issues all at once."

Any news on this? I tried fastclick, vclick and changed mousedown to touchstart/end but I just can't get to kill anything..

Will you be able to assist please? Hoping it's just a minor change somewhere..
Thanks so much!!

**Comment by MattSurabian** [comment]
This is totally resolved on the pixie branch. There are two small race condition bugs I just haven't had time to fix but I think the bulk of the changes there are probably more valuable so I'll make sure to get that merged this weekend.

How is the mobile experience on http://duckhuntjs.com? That's the deployment location of the pixi branch.

**Comment by emotality** [comment]
Wow I didn't even know that existed lol.. MY BAD!
Thats working more than perfect! :+1: Thanks!

**Comment by MattSurabian** [comment]
No worries, it's my fault. I haven't linked my site to it or merged that branch :-/ just been pulled away on other stuff. Glad to hear that one is working well!

**Comment by MattSurabian** [comment]
No worries, it's my fault. I haven't linked my site to it or merged that branch :-/ just been pulled away on other stuff. Glad to hear that one is working well!

**Comment by MattSurabian** [comment]
No worries, it's my fault. I haven't linked my site to it or merged that branch :-/ just been pulled away on other stuff. Glad to hear that one is working well and sorry for the confusion.
