### ISSUE TITLE
Screen Flicker on Mobiles

### ISSUE THREAD

**Issue by SabaRG** [MattSurabian/DuckHunt-JS#21]
I open this game on my chrome browser in android and it have many flicker, how can we fix it?

**Comment by MattSurabian** [comment]
Could you share what device you're using and what version of chrome? My main phone is a Moto G third generation with Chrome 54 and I don't see any flicker other than the intentional flash when touching the screen.

I have access to a device lab though so I'll try to replicate later this week.

**Comment by MattSurabian** [comment]
I've recently updated all the deps including PIXI and wonder if that may have solved this issue. I never was able to repro.

**Comment by MattSurabian** [comment]
Closing from inactivity, assuming this is just the intentional flash that occurs when clicking or touching the screen. Please reopen or comment if you're able to repro.
