### ISSUE TITLE
Restart option

### ISSUE THREAD

**Issue by bparkis167** [MattSurabian/DuckHunt-JS#29]
It would be nice if the game had a restart option after the game over splash screen.

**Comment by MattSurabian** [comment]
Good call! Would you expect your score to reset to 0? If so I think it can be as simple as a button that reloads the page, otherwise i'd just reset the level pointer.

**Comment by bparkis167** [comment]
Yeah the score should reset to zero after a game over. A button that reloads the page is a good idea.

**Comment by MattSurabian** [comment]
This is now live on production: https://duckhuntjs.com
