### ISSUE TITLE
Weapen.spread isn't used?

### ISSUE THREAD

**Issue by PanManAms** [MattSurabian/DuckHunt-JS#3]
Hi!
I tried adjusting the spread parameter of a gun, but this doesn't seem to be used?
The duck die function looks for a click on the duck, not near.
Right?

**Comment by MattSurabian** [comment]
That's correct @PanManAms.Sometime ago I had a branch that implemented new weapons like shotguns and canons (HUGE spread) and refactored the code to actually use spread but I lost that branch so I'll need to redo that work and I've been putting it off.

I'll try to get something together on this in the next few days!

**Comment by PanManAms** [comment]
Its not really important ATM, I was just toying around. But good to hear you are still playing with this! :)

**Comment by MattSurabian** [comment]
@PanManAms Checkout #4. Having come back to this code there's so much I would rewrite, and probably will, but that's at least a simple and quick implementation to play around with. Do you have any ideas for UI to switch weapons or a way to indicate a weapon is reloading?

**Comment by MattSurabian** [comment]
Punting on weapons changing UI, but merged in code so that `weapons.spread` is actually used now.
