### ISSUE TITLE
npm run audio - command error

### ISSUE THREAD

**Issue by leodak** [MattSurabian/DuckHunt-JS#43]
> gulp audio

[21:54:22] Using gulpfile ~/Downloads/DuckHunt-JS-master/gulpfile.js
[21:54:22] Starting 'audio'...
[21:54:22] Starting '<anonymous>'...
(node:20657) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[21:54:22] '<anonymous>' errored after 16 ms
[21:54:22] Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[21:54:22] 'audio' errored after 19 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DuckHunt-JS@3.1.0 audio: `gulp audio`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the DuckHunt-JS@3.1.0 audio script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Above is error

**Comment by IAluI** [comment]
@leodak
1. install ffmpeg https://ffmpeg.org/download.html
2. configure enveroment variable (in Windows this variables named "Path")
3. rewrite task 'audio':
```
gulp.task('audio', gulp.parallel(function(cb) {
  var files = glob.sync('./src/assets/sounds/*.mp3');
  var outputPath = './dist/audio';
  var opts = {
    output: outputPath,
    path: './',
    format: 'howler2',
    'export': 'ogg,mp3',
    loop: ['quacking', 'sniff']
  };

  return audiosprite(files, opts, function(err, obj) {
    if (err) {
      console.error(err);
    }

    return fs.writeFile('./dist/audio' + '.json', JSON.stringify(obj, null, 2), cb);
  });
}));
```
4. profit!

**Comment by MattSurabian** [comment]
Sorry for the delayed response here and thanks for jumping in @IAluI ! I've updated the master branch to account for the new function signature and add the callback.

**Comment by MattSurabian** [comment]
@leodak Updated to fix this issue here https://github.com/MattSurabian/DuckHunt-JS/commit/edbb71e38407f0d761e60f13ad27fd4c3952257b
