### ISSUE TITLE
npm run images error

### ISSUE THREAD

**Issue by jorisgraat** [MattSurabian/DuckHunt-JS#44]
> npm run images

[10:12:51] Using gulpfile ~/sites/kerstactie-2020/gulpfile.js
[10:12:51] Starting 'images'...
[10:12:51] Starting '<anonymous>'...
[10:12:51] '<anonymous>' errored after 8.22 ms
[10:12:51] ReferenceError: connect is not defined
    at /Users/joris/sites/kerstactie-2020/gulpfile.js:37:11
    at bound (domain.js:427:14)
    at runBound (domain.js:440:12)
    at asyncRunner (/Users/joris/sites/kerstactie-2020/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[10:12:51] 'images' errored after 10 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DuckHunt-JS@3.1.0 images: `gulp images`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the DuckHunt-JS@3.1.0 images script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jorisgraat** [comment]
@MattSurabian Hi! Is it possible for you to take a look? Thanks!

**Comment by Ellarddekoeijer** [comment]
I believe that in the future you can do this to get it working.
`npm i gulp-connect --save`
and then add
`var connect = require('gulp-connect');`
to the gulpfile.js

**_note that you need to have TexturePacker running locally, it should be able to run from anywhere so add it to your path_**

**Comment by IAluI** [comment]
@jorisgraat 
1. install TexturePacker https://www.codeandweb.com/texturepacker/download
2. add path to folder with TexturePacker.exe to environment variable "Path" (in other system you must do similar operation, ask google about it)
3. rewrite task 'images':
```
gulp.task('images', shell.task([
  'TexturePacker --version || echo ERROR: TexturePacker not found, install TexturePacker',
  'TexturePacker --disable-rotation --data dist/sprites.json --format json --sheet dist/sprites.png src/assets/images'
]));
```
4. profit!

**Comment by MattSurabian** [comment]
Thanks again to awesome community members @IAluI and @Ellarddekoeijer! Sorry I have been delayed on this one @jorisgraat. I have just pushed a patch that should fix this https://github.com/MattSurabian/DuckHunt-JS/commit/9a934de3bdfb55e4ee31e593524978d909aac001 

A small nitpick in the recommendations above is that this should be a dev dependency not a runtime one, so the correct command to run would be `npm i gul-connect --save-dev`. Now that it's added to package json though folks shouldn't have to think about it and this will "just work" going forward.
