### ISSUE TITLE
Change Listen IP and port

### ISSUE THREAD

**Issue by jared-bloomer** [MattSurabian/DuckHunt-JS#53]
I have found in `webpack.config.js` I can change the port the server listens on, however it always starts up with 127.0.0.1 (localhost) as the IP to listen on. Where is the setting so I change that to another IP or 0.0.0.0 for all IPs?

**Comment by MattSurabian** [comment]
Hi @jared-bloomer! You're right to look in `webpack.config.js`! Currently I'm taking advantage of a custom port setting  on line 47, this `devServer` block is where you could specify the host per the webpack dev server configuration: https://webpack.js.org/configuration/dev-server/ If memory serves the property can be specified there as `host: '0.0.0.0'` or whatever IP you desire. Then when you `npm start` webpack devServer should respect that setting within the `devServer` block just as it does for the port :+1:

**Comment by MattSurabian** [comment]
Also, feel free to re-open if this doesn't work for you; the version of devServer in this project is quite old and in need of an upgrade anyway.
